accounts/urls.py
from django.urls import include, re_path
from django.urls import path

from . import views
from .forms import LoginForm

app_name = "accounts"

urlpatterns = [re_path(r'^login/$',
                   views.LoginView.as_view(success_url='/'),
                   name='login',
                   kwargs={'authentication_form': LoginForm}),
               re_path(r'^register/$',
                   views.RegisterView.as_view(success_url="/"),
                   name='register'),
               re_path(r'^logout/$',
                   views.LogoutView.as_view(),
                   name='logout'),
               path(r'account/result.html',
                    views.account_result,
                    name='result'),
               re_path(r'^forget_password/$',
                   views.ForgetPasswordView.as_view(),
                   name='forget_password'),
               re_path(r'^forget_password_code/$',
                   views.ForgetPasswordEmailCode.as_view(),
                   name='forget_password_code'),
               ]

blog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from . import views

app_name = "blog"
urlpatterns = [
    path(
        '', 
        views.HomePage.as_view(),
        name='home'
    ),
    path(
        r'index/',
        views.IndexView.as_view(),
        name='index'),
    path(
        r'page/<int:page>/',
        views.IndexView.as_view(),
        name='index_page'),
    path(
        r'article/<int:year>/<int:month>/<int:day>/<int:article_id>.html',
        views.ArticleDetailView.as_view(),
        name='detailbyid'),
    path(
        r'category/<slug:category_name>.html',
        views.CategoryDetailView.as_view(),
        name='category_detail'),
    path(
        r'category/<slug:category_name>/<int:page>.html',
        views.CategoryDetailView.as_view(),
        name='category_detail_page'),
    path(
        r'author/<author_name>.html',
        views.AuthorDetailView.as_view(),
        name='author_detail'),
    path(
        r'author/<author_name>/<int:page>.html',
        views.AuthorDetailView.as_view(),
        name='author_detail_page'),
    path(
        r'tag/<slug:tag_name>.html',
        views.TagDetailView.as_view(),
        name='tag_detail'),
    path(
        r'tag/<slug:tag_name>/<int:page>.html',
        views.TagDetailView.as_view(),
        name='tag_detail_page'),
    path(
        'archives.html',
        cache_page(
            60 * 60)(
            views.ArchivesView.as_view()),
        name='archives'),
    path(
        'aboutus.html',
            views.AboutUsView.as_view(),
        name='aboutus'),
    path(
        'aboutorg.html',
            views.AboutOrgView.as_view(),
        name='aboutOrg'),
    path(
        'aboutteam.html',
            views.AboutTeamView.as_view(),
        name='aboutTeam'),
    path(
        'contactus.html',
            views.ContactUsView.as_view(),
        name='contactus'),
    path(
        'links.html',
        views.LinkListView.as_view(),
        name='links'),
    path(
        r'upload',
        views.fileupload,
        name='upload'),
]

djangoblog/urls.py
from django.conf import settings
from django.urls import include, re_path
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap
from django.urls import include

from djangoblog.admin_site import admin_site
from djangoblog.feeds import DjangoBlogFeed
from djangoblog.sitemap import StaticViewSitemap, ArticleSiteMap, CategorySiteMap, TagSiteMap, UserSiteMap

sitemaps = {

    'blog': ArticleSiteMap,
    'Category': CategorySiteMap,
    'Tag': TagSiteMap,
    'User': UserSiteMap,
    'static': StaticViewSitemap
}

handler404 = 'blog.views.page_not_found_view'
handler500 = 'blog.views.server_error_view'
handle403 = 'blog.views.permission_denied_view'
urlpatterns = [
                  re_path(r'^admin/', admin_site.urls),
                  re_path(r'', include('blog.urls', namespace='blog')),
                  re_path(r'mdeditor/', include('mdeditor.urls')),
                  re_path(r'', include('comments.urls', namespace='comment')),
                  re_path(r'', include('accounts.urls', namespace='account')),
                  re_path(r'', include('oauth.urls', namespace='oauth')),
                  re_path(r'^sitemap\.xml$', sitemap, {'sitemaps': sitemaps},
                      name='django.contrib.sitemaps.views.sitemap'),
                  re_path(r'^feed/$', DjangoBlogFeed()),
                  re_path(r'^rss/$', DjangoBlogFeed()),
                  re_path(r'^search', include('haystack.urls'), name='search'),
                  re_path(r'', include('servermanager.urls', namespace='servermanager')),
                  re_path(r'', include('owntracks.urls', namespace='owntracks'))
              ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

templates/share_layout/adsense.html
<aside id="text-2" class="widget widget_text"><h3 class="widget-title">Google AdSense</h3>
    <div class="textwidget">

        {{ GOOGLE_ADSENSE_CODES }}
    </div>
</aside>

templates/share_layout/analyticscode.html
<script type="text/javascript">
    (function (i, s, o, g, r, a, m) {
        i['GoogleAnalyticsObject'] = r;
        i[r] = i[r] || function () {
            (i[r].q = i[r].q || []).push(arguments)
        }, i[r].l = 1 * new Date();
        a = s.createElement(o),
            m = s.getElementsByTagName(o)[0];
        a.async = 1;
        a.src = g;
        m.parentNode.insertBefore(a, m)
    })(window, document, 'script', 'https://www.google-analytics.com/analytics.js', 'ga');

    ga('create', 'UA-27354903-4', 'auto');
    ga('send', 'pageview');
    var _hmt = _hmt || [];
    (function () {
        var hm = document.createElement("script");
        hm.src = "https://hm.baidu.com/hm.js?30dd00aec5f76607ba37c6770ae48e45";
        var s = document.getElementsByTagName("script")[0];
        s.parentNode.insertBefore(hm, s);
    })();
</script>
<a href="https://tongji.baidu.com/sc-web/3478620/home/ico?siteId=11261596" target="_blank" rel="nofollow">百度统计</a>

templates/share_layout/base.html
{% load static %}
{% load cache %}
{% load compress %}
<!DOCTYPE html>
<!--[if IE 7]>
<html class="ie ie7" lang="zh-CN"
      prefix="og: http://ogp.me/ns# fb: http://ogp.me/ns/fb# article: http://ogp.me/ns/article#">
<![endif]-->
<!--[if IE 8]>
<html class="ie ie8" lang="zh-CN"
      prefix="og: http://ogp.me/ns# fb: http://ogp.me/ns/fb# article: http://ogp.me/ns/article#">
<![endif]-->
<!--[if !(IE 7) & !(IE 8)]><!-->
<html lang="zh-CN" prefix="og: http://ogp.me/ns# fb: http://ogp.me/ns/fb# article: http://ogp.me/ns/article#">
<!--<![endif]-->
<head>
    <meta charset="UTF-8"/>
    <meta name="viewport" content="width=device-width"/>
    {% block header %}
    {% endblock %}
    <link rel="profile" href="http://gmpg.org/xfn/11"/>

    <!--[if lt IE 9]>
    <script src="{% static 'blog/js/html5.js' %}" type="text/javascript"></script>
    <![endif]-->

    <link rel="alternate" type="application/rss+xml" title="{{ SITE_NAME }} &raquo; Feed"
          href="/feed"/>
    <link rel='stylesheet preload' as="font" id='twentytwelve-fonts-css'
          href='{% static 'blog/fonts/fonts.css' %}'
          type='text/css' media='all'/>

    <!--Latest compiled and minified CSS--> 
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- Optional theme-->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    {% compress css %}

        <link rel='stylesheet' id='twentytwelve-style-css' href='{% static 'blog/css/style.css' %}' type='text/css'
              media='all'/>
        <link href="{% static 'blog/css/oauth_style.css' %}" rel="stylesheet">
        {% comment %}<script src="https://cdn.rawgit.com/google/code-prettify/master/loader/run_prettify.js"></script>{% endcomment %}
        <!--[if lt IE 9]>
        <link rel='stylesheet' id='twentytwelve-ie-css'  href='{% static 'blog/css/ie.css' %}' type='text/css' media='all' />
        <![endif]-->
        <link rel="stylesheet" href="{% static 'pygments/default.css' %}"/>
        <link rel="stylesheet" href="{% static 'blog/css/nprogress.css' %}">
        {% block compress_css %}
        {% endblock %}
    {% endcompress %}
</head>

<body class="home blog custom-font-enabled">
<div id="page" class="hfeed site" style="max-width: 80%;">
    <header id="masthead" class="site-header" role="banner">
        <div class="row">
            <div class="col-sm-6">
                <h1 class="site-title" style=""><a href="/" title="{{ SITE_NAME }}" rel="home">
                    <img style="width:15vw;" src="{% static 'blog/img/AAL(2).png' %} ">
                </a>
                </h1>
            </div>

            <div class="col-sm-6" style="text-align:right">
                <ul class = "base-li">
                    <li>
                        <a href="/admin/" rel="nofollow">Admin</a></li>
                    {% if user.is_authenticated %}
                    <!-- 登出 -->
                        <li><a href="{% url "account:logout" %}" rel="nofollow">log out</a>
                        </li>
                    {% else %}
                    <!-- 登录 -->
                        <li><a href="{% url "account:login" %}" rel="nofollow">log in</a></li>
                    {% endif %}
                </ul>

            </div>
        </div>

        {% cache 36000 nav %}
            {% include 'share_layout/nav.html' %}
        {% endcache %}

    </header><!-- #masthead -->
    <div id="main" class="wrapper">

        {% block content %}
        {% endblock %}


        {% block sidebar %}
        {% endblock %}


    </div><!-- #main .wrapper -->
    {% include 'share_layout/footer.html' %}
</div><!-- #page -->

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
 

</body>
<footer>
    {% compress js %}
        <script type="text/javascript" src="{% static 'blog/js/jquery-3.6.0.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'blog/js/nprogress.js' %}"></script>
        <script src="{% static 'blog/js/blog.js' %}" type="application/javascript"></script>
        <script src="{% static 'blog/js/navigation.js' %}" type="application/javascript"></script>
        {% block compress_js %}
        {% endblock %}
    {% endcompress %}
    {% block footer %}
    {% endblock %}
</footer>
</html>

templates/share_layout/base_account.html
<!DOCTYPE html>
<html>
<head>
    {% load static %}
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">
    <meta name="robots" content="noindex">
    <title>{{ SITE_NAME }} | {{ SITE_DESCRIPTION }}</title>
    <link href="{% static 'account/css/account.css' %}" rel="stylesheet">
    {% load compress %}
    {% compress css %}
        <!-- Bootstrap core CSS -->
        <link href="{% static 'assets/css/bootstrap.min.css' %}" rel="stylesheet">
        <link href="{% static 'blog/css/oauth_style.css' %}" rel="stylesheet">
        <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
        <link href="{% static 'assets/css/ie10-viewport-bug-workaround.css' %}" rel="stylesheet">
        <!-- TODC Bootstrap core CSS -->
        <link href="{% static 'assets/css/todc-bootstrap.min.css' %}" rel="stylesheet">
        <!-- Custom styles for this template -->
        <link href="{% static 'assets/css/signin.css' %}" rel="stylesheet">
    {% endcompress %}
    {% compress js %}
        <script src="{% static 'assets/js/ie10-viewport-bug-workaround.js' %}"></script>
        <script src="{% static 'assets/js/ie-emulation-modes-warning.js' %}"></script>
    {% endcompress %}
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>

<body>
{% block content %}
{% endblock %}

<!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->

</body>
    <script type="text/javascript" src="{% static 'blog/js/jquery-3.6.0.min.js' %}"></script>
    <script src="{% static 'account/js/account.js' %}" type="text/javascript"></script>
</html>

templates/share_layout/footer.html
<footer id="colophon" role="contentinfo">
    <div class="site-info" style="text-align: center">
        Copyright&copy;&nbsp;{{ CURRENT_YEAR }}&nbsp;
        <a href="/" target="blank">{{ SITE_NAME }}</a>
        &nbsp;|&nbsp;

        <a href="/links.html" title="Links" rel="nofollow" target="_blank">
            Links
        </a>
        

    </div>
    <!--github, ins, linkedin etc links-->
    
</footer><!-- #colophon -->

templates/share_layout/nav.html
<nav id="site-navigation" class="main-navigation" role="navigation">
    <button class="menu-toggle">Menu</button>
    <a class="assistive-text" href="#content" title="跳至正文">跳至正文</a>
    <div class="menu-%e8%8f%9c%e5%8d%95-container">
        <ul id="menu-%e8%8f%9c%e5%8d%95" class="nav-menu">
            <li id="menu-item-3498"
                class="menu-item menu-item-type-custom menu-item-object-custom current-menu-item current_page_item menu-item-home menu-item-3498">
                <a href="/">Homepage</a>
            </li>

            {% load blog_tags %}
            {% query nav_category_list parent_category=None as root_categorys %}
            {% for node in root_categorys %}
                {% include 'share_layout/nav_node.html' %}
            {% endfor %}
            {% if nav_pages %}
                {% for node in nav_pages %}
                    <li id="menu-item-{{ node.pk }}"
                        class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-has-children menu-item-{{ node.pk }}">
                        <a href="{{ node.get_absolute_url }}">{{ node.title }}</a>
                    </li>
                {% endfor %}
            {% endif %}
            <!--About us-->
            <li class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-has-children">

                <a href="{% url "blog:aboutus" %}">About Us</a>
            </li>
            <!--Contact us-->
            <li class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-has-children">

                <a href="{% url "blog:contactus" %}">Contact Us</a>
            </li>
            <!--explore more-->
            <li class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-has-children">

                <a>Explore More</a>
                <ul class="sub_menu">
                    <!--Youtube links-->
                    <li class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-has-children">

                        <a href="https://www.youtube.com/channel/UCajF0sTKqf8ESwUlYqPJWeQ/featured" target="_blank" rel="noopener noreferrer">Youtube</a>
                    </li>
                    <!--Twitter Links-->
                    <li class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-has-children">

                        <a href="https://twitter.com/leaders_asian" target="_blank" rel="noopener noreferrer">Twitter</a>
                    </li>
                    <!--Ins links-->
                    <li class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-has-children">

                        <a href="https://www.instagram.com/aaleaders0/" target="_blank" rel="noopener noreferrer">Instgram</a>
                    </li>

                    <!--Linkedin links-->
                    <li class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-has-children">

                        <a href="https://www.linkedin.com/company/asian-american-leaders-association" target="_blank" rel="noopener noreferrer">linkedin</a>
                    </li>

                    
                </ul>
            </li>
            <!--article by date-->
            <li class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-has-children">

                <a href="{% url "blog:archives" %}">Blog</a>
            </li>
            <!--search-->
            <li class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-has-children" style="position: auto;">
                <form role="search" method="get" id="searchform" class="searchform" action="/search">
                        <div>
                            <label class="screen-reader-text" for="s">Search：</label>
                            <input type="text" value="" name="q" id="q"/>
                            <input type="submit" id="searchsubmit" value="Search"/>
                        </div>
                </form>
            </li>
        </ul>
    </div>
</nav><!-- #site-navigation -->

templates/share_layout/nav_node.html
<li id="menu-item-{{ node.pk }}"
    class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-has-children menu-item-{{ node.pk }}">
    <a href="{{ node.get_absolute_url }}">{{ node.name }}</a>
    {% load blog_tags %}
    {% query nav_category_list parent_category=node as child_categorys %}
    {% if child_categorys %}

        <ul class="sub-menu">
            {% for child in child_categorys %}
                {% with node=child template_name="share_layout/nav_node.html" %}
                    {% include template_name %}
                {% endwith %}
            {% endfor %}

        </ul>
    {% endif %}
</li>