accounts/urls.py
from django.urls import include, re_path
from django.urls import path

from . import views
from .forms import LoginForm

app_name = "accounts"

urlpatterns = [re_path(r'^login/$',
                   views.LoginView.as_view(success_url='/'),
                   name='login',
                   kwargs={'authentication_form': LoginForm}),
               re_path(r'^register/$',
                   views.RegisterView.as_view(success_url="/"),
                   name='register'),
               re_path(r'^logout/$',
                   views.LogoutView.as_view(),
                   name='logout'),
               path(r'account/result.html',
                    views.account_result,
                    name='result'),
               re_path(r'^forget_password/$',
                   views.ForgetPasswordView.as_view(),
                   name='forget_password'),
               re_path(r'^forget_password_code/$',
                   views.ForgetPasswordEmailCode.as_view(),
                   name='forget_password_code'),
               ]

blog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from . import views

app_name = "blog"
urlpatterns = [
    path(
        '', 
        views.HomePage.as_view(),
        name='home'
    ),
    path(
        r'index/',
        views.IndexView.as_view(),
        name='index'),
    path(
        r'page/<int:page>/',
        views.IndexView.as_view(),
        name='index_page'),
    path(
        r'article/<int:year>/<int:month>/<int:day>/<int:article_id>.html',
        views.ArticleDetailView.as_view(),
        name='detailbyid'),
    path(
        r'category/<slug:category_name>.html',
        views.CategoryDetailView.as_view(),
        name='category_detail'),
    path(
        r'category/<slug:category_name>/<int:page>.html',
        views.CategoryDetailView.as_view(),
        name='category_detail_page'),
    path(
        r'author/<author_name>.html',
        views.AuthorDetailView.as_view(),
        name='author_detail'),
    path(
        r'author/<author_name>/<int:page>.html',
        views.AuthorDetailView.as_view(),
        name='author_detail_page'),
    path(
        r'tag/<slug:tag_name>.html',
        views.TagDetailView.as_view(),
        name='tag_detail'),
    path(
        r'tag/<slug:tag_name>/<int:page>.html',
        views.TagDetailView.as_view(),
        name='tag_detail_page'),
    path(
        'archives.html',
        cache_page(
            60 * 60)(
            views.ArchivesView.as_view()),
        name='archives'),
    path(
        'aboutus.html',
            views.AboutUsView.as_view(),
        name='aboutus'),
    path(
        'aboutorg.html',
            views.AboutOrgView.as_view(),
        name='aboutOrg'),
    path(
        'aboutteam.html',
            views.AboutTeamView.as_view(),
        name='aboutTeam'),
    path(
        'contactus.html',
            views.ContactUsView.as_view(),
        name='contactus'),
    path(
        'links.html',
        views.LinkListView.as_view(),
        name='links'),
    path(
        r'upload',
        views.fileupload,
        name='upload'),
]

djangoblog/urls.py
from django.conf import settings
from django.urls import include, re_path
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap
from django.urls import include

from djangoblog.admin_site import admin_site
from djangoblog.feeds import DjangoBlogFeed
from djangoblog.sitemap import StaticViewSitemap, ArticleSiteMap, CategorySiteMap, TagSiteMap, UserSiteMap

sitemaps = {

    'blog': ArticleSiteMap,
    'Category': CategorySiteMap,
    'Tag': TagSiteMap,
    'User': UserSiteMap,
    'static': StaticViewSitemap
}

handler404 = 'blog.views.page_not_found_view'
handler500 = 'blog.views.server_error_view'
handle403 = 'blog.views.permission_denied_view'
urlpatterns = [
                  re_path(r'^admin/', admin_site.urls),
                  re_path(r'', include('blog.urls', namespace='blog')),
                  re_path(r'mdeditor/', include('mdeditor.urls')),
                  re_path(r'', include('comments.urls', namespace='comment')),
                  re_path(r'', include('accounts.urls', namespace='account')),
                  re_path(r'', include('oauth.urls', namespace='oauth')),
                  re_path(r'^sitemap\.xml$', sitemap, {'sitemaps': sitemaps},
                      name='django.contrib.sitemaps.views.sitemap'),
                  re_path(r'^feed/$', DjangoBlogFeed()),
                  re_path(r'^rss/$', DjangoBlogFeed()),
                  re_path(r'^search', include('haystack.urls'), name='search'),
                  re_path(r'', include('servermanager.urls', namespace='servermanager')),
                  re_path(r'', include('owntracks.urls', namespace='owntracks'))
              ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

blog/models.py
import logging
from abc import abstractmethod

from django.conf import settings
from django.core.exceptions import ValidationError
from django.db import models
from django.urls import reverse
from django.utils.timezone import now
from django.utils.translation import gettext_lazy as _
from mdeditor.fields import MDTextField
from uuslug import slugify

from djangoblog.utils import cache_decorator, cache
from djangoblog.utils import get_current_site

logger = logging.getLogger(__name__)


class LinkShowType(models.TextChoices):
    I = ('i', '首页')
    L = ('l', '列表页')
    P = ('p', '文章页面')
    A = ('a', '全站')
    S = ('s', '友情链接页面')


class BaseModel(models.Model):
    id = models.AutoField(primary_key=True)
    created_time = models.DateTimeField('创建时间', default=now)
    last_mod_time = models.DateTimeField('修改时间', default=now)

    def save(self, *args, **kwargs):
        is_update_views = isinstance(
            self,
            Article) and 'update_fields' in kwargs and kwargs['update_fields'] == ['views']
        if is_update_views:
            Article.objects.filter(pk=self.pk).update(views=self.views)
        else:
            if 'slug' in self.__dict__:
                slug = getattr(
                    self, 'title') if 'title' in self.__dict__ else getattr(
                    self, 'name')
                setattr(self, 'slug', slugify(slug))
            super().save(*args, **kwargs)

    def get_full_url(self):
        site = get_current_site().domain
        url = "https://{site}{path}".format(site=site,
                                            path=self.get_absolute_url())
        return url

    class Meta:
        abstract = True

    @abstractmethod
    def get_absolute_url(self):
        pass


class Article(BaseModel):
    """文章"""
    STATUS_CHOICES = (
        ('d', '草稿'),
        ('p', '发表'),
    )
    COMMENT_STATUS = (
        ('o', '打开'),
        ('c', '关闭'),
    )
    TYPE = (
        ('a', '文章'),
        ('p', '页面'),
    )
    title = models.CharField('标题', max_length=200, unique=True)
    body = MDTextField('正文')
    pub_time = models.DateTimeField(
        '发布时间', blank=False, null=False, default=now)
    status = models.CharField(
        '文章状态',
        max_length=1,
        choices=STATUS_CHOICES,
        default='p')
    comment_status = models.CharField(
        '评论状态',
        max_length=1,
        choices=COMMENT_STATUS,
        default='o')
    type = models.CharField('类型', max_length=1, choices=TYPE, default='a')
    views = models.PositiveIntegerField('浏览量', default=0)
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        verbose_name='Author',
        blank=False,
        null=False,
        on_delete=models.CASCADE)
    article_order = models.IntegerField(
        '排序,数字越大越靠前', blank=False, null=False, default=0)
    show_toc = models.BooleanField("是否显示toc目录", blank=False, null=False, default=False)
    category = models.ForeignKey(
        'Category',
        verbose_name='分类',
        on_delete=models.CASCADE,
        blank=False,
        null=False)
    tags = models.ManyToManyField('Tag', verbose_name='标签集合', blank=True)

    def body_to_string(self):
        return self.body

    def __str__(self):
        return self.title

    class Meta:
        ordering = ['-article_order', '-pub_time']
        verbose_name = "文章"
        verbose_name_plural = verbose_name
        get_latest_by = 'id'

    def get_absolute_url(self):
        return reverse('blog:detailbyid', kwargs={
            'article_id': self.id,
            'year': self.created_time.year,
            'month': self.created_time.month,
            'day': self.created_time.day
        })

    @cache_decorator(60 * 60 * 10)
    def get_category_tree(self):
        tree = self.category.get_category_tree()
        names = list(map(lambda c: (c.name, c.get_absolute_url()), tree))

        return names

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)

    def viewed(self):
        self.views += 1
        self.save(update_fields=['views'])

    def comment_list(self):
        cache_key = 'article_comments_{id}'.format(id=self.id)
        value = cache.get(cache_key)
        if value:
            logger.info('get article comments:{id}'.format(id=self.id))
            return value
        else:
            comments = self.comment_set.filter(is_enable=True)
            cache.set(cache_key, comments, 60 * 100)
            logger.info('set article comments:{id}'.format(id=self.id))
            return comments

    def get_admin_url(self):
        info = (self._meta.app_label, self._meta.model_name)
        return reverse('admin:%s_%s_change' % info, args=(self.pk,))

    @cache_decorator(expiration=60 * 100)
    def next_article(self):
        # 下一篇
        return Article.objects.filter(
            id__gt=self.id, status='p').order_by('id').first()

    @cache_decorator(expiration=60 * 100)
    def prev_article(self):
        # 前一篇
        return Article.objects.filter(id__lt=self.id, status='p').first()


class Category(BaseModel):
    """文章分类"""
    name = models.CharField('分类名', max_length=30, unique=True)
    parent_category = models.ForeignKey(
        'self',
        verbose_name="父级分类",
        blank=True,
        null=True,
        on_delete=models.CASCADE)
    slug = models.SlugField(default='no-slug', max_length=60, blank=True)
    index = models.IntegerField(default=0, verbose_name="权重排序-越大越靠前")

    class Meta:
        ordering = ['-index']
        verbose_name = "分类"
        verbose_name_plural = verbose_name

    def get_absolute_url(self):
        return reverse(
            'blog:category_detail', kwargs={
                'category_name': self.slug})

    def __str__(self):
        return self.name

    @cache_decorator(60 * 60 * 10)
    def get_category_tree(self):
        """
        递归获得分类目录的父级
        :return:
        """
        categorys = []

        def parse(category):
            categorys.append(category)
            if category.parent_category:
                parse(category.parent_category)

        parse(self)
        return categorys

    @cache_decorator(60 * 60 * 10)
    def get_sub_categorys(self):
        """
        获得当前分类目录所有子集
        :return:
        """
        categorys = []
        all_categorys = Category.objects.all()

        def parse(category):
            if category not in categorys:
                categorys.append(category)
            childs = all_categorys.filter(parent_category=category)
            for child in childs:
                if category not in categorys:
                    categorys.append(child)
                parse(child)

        parse(self)
        return categorys


class Tag(BaseModel):
    """文章标签"""
    name = models.CharField('标签名', max_length=30, unique=True)
    slug = models.SlugField(default='no-slug', max_length=60, blank=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('blog:tag_detail', kwargs={'tag_name': self.slug})

    @cache_decorator(60 * 60 * 10)
    def get_article_count(self):
        return Article.objects.filter(tags__name=self.name).distinct().count()

    class Meta:
        ordering = ['name']
        verbose_name = "标签"
        verbose_name_plural = verbose_name


class Links(models.Model):
    """友情链接"""

    name = models.CharField('链接名称', max_length=30, unique=True)
    link = models.URLField('链接地址')
    sequence = models.IntegerField('排序', unique=True)
    is_enable = models.BooleanField(
        '是否显示', default=True, blank=False, null=False)
    show_type = models.CharField(
        '显示类型',
        max_length=1,
        choices=LinkShowType.choices,
        default=LinkShowType.I)
    created_time = models.DateTimeField('创建时间', default=now)
    last_mod_time = models.DateTimeField('修改时间', default=now)

    class Meta:
        ordering = ['sequence']
        verbose_name = '友情链接'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name


class SideBar(models.Model):
    """侧边栏,可以展示一些html内容"""
    name = models.CharField('标题', max_length=100)
    content = models.TextField("内容")
    sequence = models.IntegerField('排序', unique=True)
    is_enable = models.BooleanField('是否启用', default=True)
    created_time = models.DateTimeField('创建时间', default=now)
    last_mod_time = models.DateTimeField('修改时间', default=now)

    class Meta:
        ordering = ['sequence']
        verbose_name = '侧边栏'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name


class BlogSettings(models.Model):
    '''站点设置 '''
    sitename = models.CharField(
        "网站名称",
        max_length=200,
        null=False,
        blank=False,
        default='')
    site_description = models.TextField(
        "网站描述",
        max_length=1000,
        null=False,
        blank=False,
        default='')
    site_seo_description = models.TextField(
        "网站SEO描述", max_length=1000, null=False, blank=False, default='')
    site_keywords = models.TextField(
        "网站关键字",
        max_length=1000,
        null=False,
        blank=False,
        default='')
    article_sub_length = models.IntegerField("文章摘要长度", default=300)
    sidebar_article_count = models.IntegerField("侧边栏文章数目", default=10)
    sidebar_comment_count = models.IntegerField("侧边栏评论数目", default=5)
    show_google_adsense = models.BooleanField('是否显示谷歌广告', default=False)
    google_adsense_codes = models.TextField(
        '广告内容', max_length=2000, null=True, blank=True, default='')
    open_site_comment = models.BooleanField('是否打开网站评论功能', default=True)
    beiancode = models.CharField(
        '备案号',
        max_length=2000,
        null=True,
        blank=True,
        default='')
    analyticscode = models.TextField(
        "网站统计代码",
        max_length=1000,
        null=False,
        blank=False,
        default='')
    show_gongan_code = models.BooleanField(
        '是否显示公安备案号', default=False, null=False)

blog/forms.py
import logging

from django import forms
from haystack.forms import SearchForm

logger = logging.getLogger(__name__)


class BlogSearchForm(SearchForm):
    querydata = forms.CharField(required=True)

    def search(self):
        datas = super(BlogSearchForm, self).search()
        if not self.is_valid():
            return self.no_query_found()

        if self.cleaned_data['querydata']:
            logger.info(self.cleaned_data['querydata'])
        return datas

templates/blog/article_archives.html
{% extends 'share_layout/base.html' %}
{% load blog_tags %}
{% load cache %}
{% block header %}

    <title>Article Archive | {{ SITE_DESCRIPTION }}</title>

    <meta name="description" content="{{ SITE_SEO_DESCRIPTION }}"/>
    <meta name="keywords" content="{{ SITE_KEYWORDS }}"/>
    <meta property="og:type" content="blog"/>
    <meta property="og:title" content="{{ SITE_NAME }}"/>
    <meta property="og:description" content="{{ SITE_DESCRIPTION }}"/>
    <meta property="og:url" content="{{ SITE_BASE_URL }}"/>
    <meta property="og:site_name" content="{{ SITE_NAME }}"/>

{% endblock %}
{% block content %}
    <div id="primary" class="site-content">
        <div id="content" role="main">

            <header class="archive-header">

                <p class="archive-title">Blog</p><!--文章归档-->
            </header><!-- .archive-header -->

            <div class="entry-content">

                {% regroup article_list by pub_time.year as year_post_group %}
                <ul>
                    {% for year in year_post_group %}
                        <li>{{ year.grouper }} 
                            {% regroup year.list by pub_time.month as month_post_group %}
                            <ul>
                                {% for month in month_post_group %}
                                    <li>{{ month.grouper }} 
                                        <ul>
                                            {% for article in month.list %}
                                                <li><a href="{{ article.get_absolute_url }}">{{ article.title }}</a>
                                                </li>
                                            {% endfor %}
                                        </ul>
                                    </li>
                                {% endfor %}
                            </ul>
                        </li>
                    {% endfor %}
                </ul>
            </div>
        </div><!-- #content -->
    </div><!-- #primary -->

{% endblock %}


{% block sidebar %}
    {% load_sidebar user 'i' %}
{% endblock %}

templates/blog/article_detail.html
{% extends 'share_layout/base.html' %}
{% load blog_tags %}

{% block header %}
    <title>{{ article.title }} | {{ SITE_DESCRIPTION }}</title>
    <meta property="og:type" content="article"/>
    <meta property="og:title" content="{{ article.title }}"/>


    <meta property="og:description" content="{{ article.body|custom_markdown|striptags|truncatewords:1 }}"/>
    <meta property="og:url"
          content="{{ article.get_full_url }}"/>
    <meta property="article:published_time" content="{% datetimeformat article.pub_time %}"/>
    <meta property="article:modified_time" content="{% datetimeformat article.pub_time %}"/>
    <meta property="article:author" content="{{ article.author.get_full_url }}"/>
    <meta property="article:section" content="{{ article.category.name }}"/>
    {% for t in article.tags.all %}
        <meta property="article:tag" content="{{ t.name }}"/>
    {% endfor %}
    <meta property="og:site_name" content="{{ SITE_NAME }}"/>

    <meta name="description" content="{{ article.body|custom_markdown|striptags|truncatewords:1 }}"/>
    {% if article.tags %}
        <meta name="keywords" content="{{ article.tags.all|join:"," }}"/>
    {% else %}
        <meta name="keywords" content="{{ SITE_KEYWORDS }}"/>
    {% endif %}

{% endblock %}
{% block content %}
    <div id="primary" class="site-content">
        <div id="content" role="main">
            {% load_article_detail article False user %}

            {% if article.type == 'a' %}
                <nav class="nav-single">
                    <h3 class="assistive-text">Article Index</Article></h3>
                    {% if next_article %}

                        <span class="nav-previous"><a href="{{ next_article.get_absolute_url }}" rel="prev"><span
                                class="meta-nav">&larr;</span> {{ next_article.title }}</a></span>
                    {% endif %}
                    {% if prev_article %}
                        <span class="nav-next"><a href="{{ prev_article.get_absolute_url }}"
                                                  rel="next">{{ prev_article.title }} <span
                                class="meta-nav">&rarr;</span></a></span>
                    {% endif %}
                </nav><!-- .nav-single -->
            {% endif %}

        </div><!-- #content -->
        {% if article.comment_status == "o" and OPEN_SITE_COMMENT %}


            {% include 'comments/tags/comment_list.html' %}
            {% if user.is_authenticated %}
                {% include 'comments/tags/post_comment.html' %}
            {% else %}
                <div class="comments-area">
                    <h3 class="comment-meta">You are not logged in yet, please leava a comment after you <a
                            href="{% url "account:login" %}?next={{ request.get_full_path }}" rel="nofollow">login</a>
                    </h3>

                    {% load oauth_tags %}
                    {% load_oauth_applications request %}

                </div>
            {% endif %}
        {% endif %}
    </div><!-- #primary -->

{% endblock %}

{% block sidebar %}
    {% load_sidebar user "p" %}
{% endblock %}

templates/blog/article_index.html
{% extends 'share_layout/base.html' %}
{% load blog_tags %}
{% load cache %}
{% block header %}
    {% if tag_name %}
        <title>{{ page_type }}:{{ tag_name }} | {{ SITE_DESCRIPTION }}</title>
        {% comment %}<meta name="description" content="{{ page_type }}:{{ tag_name }}"/>{% endcomment %}
    {% else %}
        <title>{{ SITE_NAME }} | {{ SITE_DESCRIPTION }}</title>
    {% endif %}
    <meta name="description" content="{{ SITE_SEO_DESCRIPTION }}"/>
    <meta name="keywords" content="{{ SITE_KEYWORDS }}"/>
    <meta property="og:type" content="blog"/>
    <meta property="og:title" content="{{ SITE_NAME }}"/>
    <meta property="og:description" content="{{ SITE_DESCRIPTION }}"/>
    <meta property="og:url" content="{{ SITE_BASE_URL }}"/>
    <meta property="og:site_name" content="{{ SITE_NAME }}"/>
{% endblock %}
{% block content %}
    <div id="primary" class="site-content">
        <div id="content" role="main">
            {% if page_type and tag_name %}
                <header class="archive-header">

                    <p class="archive-title">{{ page_type }}：<span>{{ tag_name }}</span></p>
                </header><!-- .archive-header -->
            {% endif %}

            {% for article in article_list %}
                {% load_article_detail article True user %}
            {% endfor %}
            

            {% if is_paginated %}
                {% load_pagination_info page_obj page_type tag_name %}

            {% endif %}
        </div><!-- #content -->
    </div><!-- #primary -->

{% endblock %}
{% block sidebar %}
    {% load_sidebar user 'i' %}
{% endblock %}

templates/blog/contact_us.html
{% extends 'share_layout/base.html' %}
{% load blog_tags %}
{% load cache %}
{% block header %}
    {% if tag_name %}
        <title>{{ page_type }}:{{ tag_name }} | {{ SITE_DESCRIPTION }}</title>
        {% comment %}<meta name="description" content="{{ page_type }}:{{ tag_name }}"/>{% endcomment %}
    {% else %}
        <title>{{ SITE_NAME }} | {{ SITE_DESCRIPTION }}</title>
    {% endif %}
    <meta name="description" content="{{ SITE_SEO_DESCRIPTION }}"/>
    <meta name="keywords" content="{{ SITE_KEYWORDS }}"/>
    <meta property="og:type" content="blog"/>
    <meta property="og:title" content="{{ SITE_NAME }}"/>
    <meta property="og:description" content="{{ SITE_DESCRIPTION }}"/>
    <meta property="og:url" content="{{ SITE_BASE_URL }}"/>
    <meta property="og:site_name" content="{{ SITE_NAME }}"/>
{% endblock %}
{% block content %}
    <div id="primary" class="site-content">
        <div id="content" role="main">
            {% if page_type and tag_name %}
                <header class="archive-header">

                    <p class="archive-title">{{ page_type }}：<span>{{ tag_name }}</span></p>
                </header><!-- .archive-header -->
            {% endif %}
        

        </div><!-- #content -->
    </div><!-- #primary -->


    <div class="main-info">
            <h1>Contact Us</h1>

            <br>
            <p>Please know that we understand the importance of being discrete. In order to maintain optimal confidentiality, please use the Message Field below to indicate your preferred method of communication. You may also send email to us: asianamericanleaders@gmail.com 
            </p>

            <br>
            <p>Please contact Asian American Leaders association if you have an interest in exploring joining with us to make contribution to our community.</p>

        
    </div>  

    
{% endblock %}

templates/blog/homepage.html
{% extends 'share_layout/base.html' %}
{% load blog_tags %}
{% load static %}
{% load cache %}
{% block header %}
    {% if tag_name %}
        <title>{{ page_type }}:{{ tag_name }} | {{ SITE_DESCRIPTION }}</title>
        {% comment %}<meta name="description" content="{{ page_type }}:{{ tag_name }}"/>{% endcomment %}
    {% else %}
        <title>{{ SITE_NAME }} | {{ SITE_DESCRIPTION }}</title>
    {% endif %}
    <meta name="description" content="{{ SITE_SEO_DESCRIPTION }}"/>
    <meta name="keywords" content="{{ SITE_KEYWORDS }}"/>
    <meta property="og:type" content="blog"/>
    <meta property="og:title" content="{{ SITE_NAME }}"/>
    <meta property="og:description" content="{{ SITE_DESCRIPTION }}"/>
    <meta property="og:url" content="{{ SITE_BASE_URL }}"/>
    <meta property="og:site_name" content="{{ SITE_NAME }}"/>

    <!--Latest compiled and minified CSS--> 
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- Optional theme-->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

       
{% endblock %}
{% block content %}
    <div id="primary" class="site-content">
        <div id="content" role="main">
            {% if page_type and tag_name %}
                <header class="archive-header">

                    <p class="archive-title">{{ page_type }}：<span>{{ tag_name }}</span></p>
                </header><!-- .archive-header -->
            {% endif %}
        

        </div><!-- #content -->
    </div><!-- #primary --> 

    <div class="row" style="">
        <div class="col-sm-8 main-info" style="width: 60%;">
            <h1>Asian American Leaders</h1>
            <br>
            <p>Asian American Leaders (AAL) 
            is a non-profit organization headquartered in 
            North Carolina, USA. Our mission is to organize 
            and unite Asian leaders working in the United States 
            to build an interactive platform for resource sharing. 
            We try to help people who want to be a leader in 
            different industries.</p>
        </div>
        <div class="col-sm-4">
            <img style="width:25vw;" src="{% static 'blog/img/pic.jpeg' %} " >   
        </div>
    </div>

    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    
    <div class="entry-content">

        <!--need to change the picture-->
        {% if article_list %}
            {% for a in article_list|slice:"0:1"%}
                <div class="col-sm-4" style="line-height: 1.2">
                    <img style="width:15vw;" src="{% static 'blog/img/blogpic1.jpg' %} " >   
                
                    <ul style="font-size: 160%;">{{ a.title }}</ul>
                    <ul style="font-size: 120%;"><a href="{{ a.get_absolute_url }}">Read more</a></ul>
                </div>
            {% endfor %}

            {% for a in article_list|slice:"1:2"%}
                <div class="col-sm-4" style="line-height: 1.2">
                    <img style="width:15vw;" src="{% static 'blog/img/blog2.jpg' %} " >   
                
                    <ul style="font-size: 160%;">{{ a.title }}</ul>
                    <ul style="font-size: 120%;"><a href="{{ a.get_absolute_url }}">Read more</a></ul>
                </div>
            {% endfor %}

            {% for a in article_list|slice:"2:3"%}
                <div class="col-sm-4" style="line-height: 1.2">
                    <img style="width:15vw;" src="{% static 'blog/img/blog3.jpg' %} " >   
                
                    <ul style="font-size: 160%;">{{ a.title }}</ul>
                    <ul style="font-size: 120%;"><a href="{{ a.get_absolute_url }}">Read more</a></ul>
                </div>
            {% endfor %}
        {% endif %}
        <br>
        <br>
    </div>

    <br>
    <br>

    

    



    <!-- Latest compiled and minified JavaScript -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
     

    
{% endblock %}